name: CD
on:
  - workflow_dispatch

jobs:
  build-and-deploy:
    name: 'Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: Install dependencies
        run: yarn install
      - name: Build site
        run: yarn build
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: live
          FOLDER: build
          CLEAN: true
