name: CI
on: [push]

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      # - name: Install dependencies
      #   run: yarn install
      # - name: Run tests
      #   run: yarn test
      #   env:
      #     CI: true
      - name: Dispatch event
        run: echo $GITHUB_BRANCH
